Iter13
MrTomSawyer/url-shortener pull request #14
Opened 2023-06-11 13:59 UTC by MrTomSawyer

2023-06-13 19:01 UTC, maxlyaptsev requested changes

2023-06-14 16:25 UTC, MrTomSawyer commented on internal/app/handler/batchInsert.go
> +			query := "INSERT INTO urls (correlationid, shorturl, originalurl) VALUES ($1, $2, $3)"
Убрал логику в сервис

2023-06-14 18:10 UTC, MrTomSawyer commented on internal/app/handler/batchInsert.go
> +func (h Handler) batchURLinsert(c *gin.Context) {
done

2023-06-14 18:20 UTC, MrTomSawyer commented on internal/app/handler/expandURL.go
> +	if err != nil || value == "" {
done

2023-06-17 16:20 UTC, merged