Iter5
MrTomSawyer/url-shortener pull request #5
Opened 2023-05-03 20:13 UTC by MrTomSawyer

2023-05-05 08:28 UTC, maxlyaptsev requested changes

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/handler/url.go
> +	id := c.Request.URL.String()[1:]
gin позволяет получить параметр по его названию

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/service/service.go
> +func NewService(repo map[string]string) *Service {
из названия непонятно за что отвечает этот пакет

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/service/url.go
> +func NewURLservice(m map[string]string) *URLservice {
рядом есть файл service.go в котором тоже есть публичный конструктор. Если он будет использоваться в качестве роутера, нужен ли публичный констурктор здесь?

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/service/url.go
> +	if _, ok := u.repo[hash]; !ok {
возможны ли здесь коллизии? Когда новый короткий url будет равен сущесвующему, но полные адреса будут отличаться

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +var repo = make(map[string]string)
нужно ли создавать переменную вне области видимости функции?  В go так не принятно, хотя в стандартных пакетах такое встречается. Но нужно четко понимать цель. Если без этого не обойтись

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/config/flags.go
> +package config
название файла немного путает, тут не только конфиг по флагам

2023-05-05 08:28 UTC, maxlyaptsev commented on cmd/shortener/service/service.go
> +type URL interface {
интерфейс объявлен, но нигде не используется, лучше его объявлять в месте конкретного использвоания
Кроме того интерфейс имеет смысл описывать во внешних относительно текущего пакетах, чтобы их изолировать. Тут же url принадлежит этому же пакету, просто выделен в отдельный файл

2023-05-05 08:47 UTC, MrTomSawyer commented on cmd/shortener/service/url.go
> +func NewURLservice(m map[string]string) *URLservice {
done

2023-05-05 08:48 UTC, MrTomSawyer commented on cmd/shortener/config/flags.go
> +package config
done

2023-05-10 08:59 UTC, maxlyaptsev commented on cmd/shortener/service/url.go
> +	shortURL := fmt.Sprintf("%s/%s", config.DefaultAddr, hash)
если запустим на новом порту, то захардкоженный таким образом адрес будет недоступен (сейчас у нас хранилище очищается, поэтому ошибку не поймать, но если оно станет персистентным, то возникнут сложности). Лучше формирование ссылки перенести на сторону ее получения

2023-05-10 12:39 UTC, MrTomSawyer commented on cmd/shortener/config/flags.go
> +var ServerAddr, DefaultAddr string
done

2023-05-10 12:39 UTC, MrTomSawyer commented on cmd/shortener/handler/url.go
> +	id := c.Request.URL.String()[1:]
done

2023-05-10 12:43 UTC, MrTomSawyer commented on cmd/shortener/service/url.go
> +	if _, ok := u.repo[hash]; !ok {
done

2023-05-10 12:43 UTC, MrTomSawyer commented on cmd/shortener/main.go
> +var repo = make(map[string]string)
done

2023-05-10 12:44 UTC, MrTomSawyer commented on cmd/shortener/service/service.go
> +type URL interface {
done

2023-05-19 14:41 UTC, merged